# Generated by Django 5.1.4 on 2025-01-08 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('tipoalojamiento', models.CharField(max_length=200)),
                ('numeropersonas', models.CharField(max_length=200)),
                ('estadoreserva', models.CharField(max_length=200)),
                ('observaciones', models.TextField()),
                ('campista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Camping.campista')),
            ],
        ),
    ]
